### ISSUE TITLE
Layer #0 (named "conv1" in the current model)

### ISSUE THREAD

**Issue by levelvc** [titu1994/MobileNetworks#1]
@titu1994 getting the following error:

ValueError: Layer #0 (named "conv1" in the current model) was found to correspond to layer conv1 in the save file. However the new layer conv1 expects 1 weights, but the saved weights have 2 elements.

It could be that your release network is out of sync.

**Comment by titu1994** [comment]
There earlier implementation was incorrect. Yesterday, the official model was released, and I am now in the process of updating the model to match the tensorflow slim definition. That is the reason the earlier weights no longer work.

On that topic, while I was able to match the definition exactly to the slim version, for some reason, the predictions are wrong.

I am currently inspecting the tensorflow graph of both and it shows that exactly same operations are being performed by both in all areas other than batchnorm (the tfslim version has a slightly more complex multiply-add graph), but that should not make a difference since the ported weights are being loaded exactly into the Keras model - and therefore the Keras graph.

I will push the code I am using for now. If you dont mind, could you try to guess what the reason is that is happening?

**Comment by titu1994** [comment]
For creating the graphs, you will need the checkpoint from here https://github.com/tensorflow/models/blob/master/slim/README.md#Pretrained (the MobileNet_v1_1.0_224 one).

Put the checkpoint file inside the _weight_extraction/checkpoint/ folder.
Run the predict_checkpoint.py script to predict on the African elephant - gives correct results.
(To see the graph - Run tensorboard on the logs directory it created and open the graph.
Shutdown tensorboard after opening the graph in localhost:6006)

Run mobilenets.py script to generate the keras graph in logs/keras/. Open tensorboard again in this directory and open a new tab at localhost:6006 to see the keras graph.

On comparison, both are the same in all regions other than batch norm.

**Comment by titu1994** [comment]
To generate weights, there are more steps involved, and can be found in the readme for the _weights_extraction folders.

**Comment by levelvc** [comment]
@titu1994 Without looking, one quick guess is to make sure that for the input the channel first setting is correct and whether there needs to be any transformation of RGB to BGR.

**Comment by titu1994** [comment]
Nevermind, it was a fault of how I was loading the BatchNorm weights. Tensorflow saves in the format [beta, gamma, running_mean, running_variance], and keras saves weights in the format [gamme, beta, running_mean, running_variance].

Since gamma and beta have the same shape, they dont through an error during weight loading. Have updated the Keras weights. 

But do not use it just yet. I will be adding a lot of extra code so maybe hold out for 1 day (I plan on supporting all 16 weights.)

**Comment by titu1994** [comment]
This is fixed now. Update will come soon.

**Comment by titu1994** [comment]
Update : Models are ready to use. All 16 models ported and can be loaded and used by changing alpha and image size now.

**Comment by levelvc** [comment]
@titu1994 thanks. Had a chance to play around with the implementation - working well. You should note that to load_model, you need to pass in the custom layers (the depthwise convolution and relu activation). The relu activation poses problems because of the lamda, thus it is best to define a function:

```
import keras.activations
keras.activations.custom_activation = relu_activation
```
And then use the function as a parameter.

**Comment by titu1994** [comment]
Hmm. I've often had trouble with save and load_model. I just prefer building the model and then loading the weights separately. 

Also, I've added it MobileNets as a PR to core Keras. So the depths layer should not be a problem.
About the activation, I will see what I can do. 

Your fix is equivalent to injecting code into the Keras activation directory, isn't it ?

**Comment by levelvc** [comment]
Yes correct, the fix is equivalent.

**Comment by titu1994** [comment]
Ok I will try it and see if it fixes load.

Regards,
Somshubra Majumdar

**Comment by mikechen66** [comment]
If a file of weights is partially downloaded, it generates the issue during the runtime  while  trying to access to the (downloaded but not completed) file with a directory.
